export const GET_CATEGORY = "GET_CATEGORY"
export const SET_CATEGORY = "SET_CATEGORY"
export const GET_CATEGORY_RESULTS = "GET_CATEGORY_RESULTS"
export const SET_CATEGORY_RESULTS = "SET_CATEGORY_RESULTS"